export const COLLECTIONS = {
  USERS: 'users',
  CHANNELS: 'channels',
  CATEGORIES: 'categories',
  CHANNEL_CATEGORIES: 'channel_categories',
  CHANNEL_CLAIMS: 'channel_claims',
  CHANNEL_CHANGE_REQUESTS: 'channel_change_requests',
  EVENTS: 'events',
  CHANNEL_DAILY_METRICS: 'channel_daily_metrics',
  CHANNEL_DAILY_SOURCE_METRICS: 'channel_daily_source_metrics',
  CHANNEL_SEARCH_QUERY_METRICS: 'channel_search_query_metrics',
  ROLLUP_STATE: 'analytics_rollup_state',
  ENRICHMENT_CACHE: 'enrichment_cache',
  BOOKMARKS: 'bookmarks',
  REPORTS: 'reports',
  AUDIT_LOGS: 'audit_logs',
  HOMEPAGE_SLOTS: 'homepage_slots',
  PROMOTION_CAMPAIGNS: 'promotion_campaigns',
  PROMOTION_RATE_CARDS: 'promotion_rate_cards',
  CAMPAIGN_IMPRESSION_DEDUP: 'campaign_impression_dedup',
  CAMPAIGN_DAILY_METRICS: 'campaign_daily_metrics',
  PAYMENT_FUNDING_ORDERS: 'payment_funding_orders',
  CAMPAIGN_FUNDING_LEDGER: 'campaign_funding_ledger',
  PAYMENT_WEBHOOK_EVENTS: 'payment_webhook_events',
  SPONSORED_IMPRESSION_DEDUP: 'sponsored_impression_dedup',
  LEDGER_TRANSACTIONS: 'ledger_transactions',
  PAYMENT_REFUNDS: 'payment_refunds',
  FUNDING_FX_RATES: 'funding_fx_rates',
  FUNDING_FX_QUOTES: 'funding_fx_quotes',
  SPONSORSHIP_LEADS: 'sponsorship_leads',
  INTEGRATION_CREDENTIALS: 'integration_credentials',
  INTEGRATION_PROVIDER_SETTINGS: 'integration_provider_settings',
  SECURITY_AUDIT_EVENTS: 'security_audit_events',
  COMMERCIAL_LEADS: 'commercial_leads',
  CHANNEL_RATE_CARDS: 'channel_rate_cards',
  MARKETPLACE_ORDERS: 'marketplace_orders',
  MARKETPLACE_FINANCIAL_EVENTS: 'marketplace_financial_events',
  MARKETPLACE_OWNER_PAYOUTS: 'marketplace_owner_payouts',
  MARKETPLACE_PAYMENT_ATTEMPTS: 'marketplace_payment_attempts',
  MARKETPLACE_DELIVERY_SUBMISSIONS: 'marketplace_delivery_submissions',
  MARKETPLACE_DELIVERY_ESCALATIONS: 'marketplace_delivery_escalations',
  OWNER_PAYOUT_METHODS: 'owner_payout_methods',
  // M11-Batch2A — owner-submitted follower-count evidence (append-only history).
  CHANNEL_AUDIENCE_SNAPSHOTS: 'channel_audience_snapshots',
  // M11-Batch3 — Cookie consent decisions (append-only audit trail).
  CONSENT_RECORDS: 'consent_records',
  // M11-Batch3 — First-party product analytics events (append-only, consented).
  ANALYTICS_EVENTS: 'analytics_events',
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
